columns:
  - hotel: category
  - is_canceled: int
  - lead_time: int
  - arrival_date_year: int
  - arrival_date_month: category
  - arrival_date_week_number: int
  - arrival_date_day_of_month: int
  - stays_in_weekend_nights: int
  - stays_in_week_nights: int
#  - adults: int
#  - children: float
#  - babies: int
  - meal: category
  - country: category
  - market_segment: category
  - distribution_channel: category
  - is_repeated_guest: int
  - previous_cancellations: int
  - previous_bookings_not_canceled: int
  - reserved_room_type: category
  - assigned_room_type: category
  - booking_changes: int
  - deposit_type: category
  - agent: float
  - company: float
  - days_in_waiting_list: int
  - customer_type: category
  - adr: float
  - required_car_parking_spaces: int
  - total_of_special_requests: int
  - reservation_status: category
  - reservation_status_date: category
  - name: category
  - email: category
  - phone-number: category
  - credit_card: category
  - total_guest: float


drop_columns:
  - name
  - email
  - phone-number
  - credit_card
  - company
  - previous_bookings_not_canceled
  - days_in_waiting_list
  - arrival_date_week_number
  - reservation_status
  - reservation_status_date
  - assigned_room_type
  - agent
  - required_car_parking_spaces
  - is_repeated_guest

numerical_columns:
  - is_canceled
  - lead_time
  - arrival_date_year
  - arrival_date_week_number
  - arrival_date_day_of_month
  - stays_in_weekend_nights
  - stays_in_week_nights
#  - adults
#  - children
#  - babies
  - is_repeated_guest
  - previous_cancellations
  - previous_bookings_not_canceled
  - booking_changes
  - agent
  - company
  - days_in_waiting_list
  - adr
  - required_car_parking_spaces
  - total_of_special_requests


categorical_columns:
  - hotel
  - arrival_date_month
  - meal
  - country
  - market_segment
  - distribution_channel
  - reserved_room_type
  - assigned_room_type
  - deposit_type
  - customer_type
  - reservation_status
  - reservation_status_date
  - name
  - email
  - phone-number
  - credit_card


num_features:
  - lead_time
  - arrival_date_year
  - arrival_date_day_of_month
  - stays_in_weekend_nights
  - stays_in_week_nights
  - previous_cancellations
  - booking_changes
  - adr
  - total_of_special_requests
  - total_guest

bin_columns:
  - country

oh_columns:
  - meal
  - market_segment
  - distribution_channel
  - deposit_type
  - customer_type

ordinal_columns:
  - hotel
  - arrival_date_month
  - reserved_room_type

custom_features_columns:
  - children
  - adults
  - babies
  - lead_time
  - meal
  - market_segment
  - distribution_channel



